services:
  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
#      - ./src/main/java/ru/zakharenko/dbpractice/webconfig/init_data.sql:/docker-entry-point-initdb.d/001.sql
    ports:
      - 5442:5432
